apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-with-empty-nodeselector.fullname" . }}-my-config
  labels:
  {{- include "app-with-empty-nodeselector.labels" . | nindent 4 }}
immutable: true
data:
  dummyconfigmapkey: {{ .Values.myConfig.dummyconfigmapkey | quote }}
  my_config.properties: |
    health.healthProbeBindAddress={{ .Values.myConfig.myConfigProperties.health.healthProbeBindAddress | quote }}
    metrics.bindAddress={{ .Values.myConfig.myConfigProperties.metrics.bindAddress | quote }}