apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-app-ingress
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "app.fullname" . }}-app-service'
            port:
              number: 8443
        path: /testpath
        pathType: Prefix
