apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config-props
  labels:
  {{- include "app.labels" . | nindent 4 }}
data:
  my.prop1: {{ .Values.configProps.myProp1 | quote }}
  my.prop2: {{ .Values.configProps.myProp2 | quote }}
  my.prop3: {{ .Values.configProps.myProp3 | quote }}
  myval.yaml: {{ .Values.configProps.myvalYaml | toYaml | indent 1 }}
