apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-service
  labels:
    app: myapp
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
