apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator.fullname" . }}-manager-config
  labels:
  {{- include "operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: {{ .Values.managerConfig.controllerManagerConfigYaml
    | toYaml | indent 1 }}
  dummyconfigmapkey: {{ tpl (.Values.managerConfig.dummyconfigmapkey) $ | quote }}